/*
 * SummaryDialog.java
 *
 * Created on December 20, 2006, 11:46 AM
 */

package gov.nih.nimh.mass_sieve.gui;

import gov.nih.nimh.mass_sieve.io.FileInformation;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author  slotta
 */
public class SummaryDialog extends Dialog {
    private ExperimentPanel expPanel;
    private ArrayList<FileInformation> fileInfos;
    
    /** Creates new form SummaryDialog */
    public SummaryDialog(ExperimentPanel ep) {
        super(ep.getMassSieveFrame(), false);
        expPanel = ep;
        initComponents();
        setTitle(expPanel.getName() + " Summary");
    }
    
    public void setFileInformation(ArrayList<FileInformation> fi) {
        fileInfos = fi;
        Collections.sort(fileInfos);
        StringBuffer sb = new StringBuffer(4096);
        sb.append("<html><table><tr><th>Experiment</th><th>File name</th><th>Analysis Program</th><th>Search Database</th><th>Total PepHits</th><th>DTA files</th></tr>");
        
        for (FileInformation fInfo:fileInfos) {
            sb.append("<tr>");
            sb.append("<td>" + fInfo.getExperiment() + "</td>");
            sb.append("<td>" + fInfo.getSourceFile() + "</td>");
            sb.append("<td>" + fInfo.getAnalysisProgram() + "</td>");
            sb.append("<td>" + fInfo.getSearchDB() + "</td>");
            sb.append("<td>" + fInfo.getPepHitCount() + "</td>");
            ArrayList<String> rawFiles = new ArrayList<String>(fInfo.getRawFiles());
            if (rawFiles.size() > 0) {
                Collections.sort(rawFiles);
                sb.append("<td>" + rawFiles.get(0) + "</td>");
                rawFiles.remove(0);
                for (String rFile:rawFiles) {
                    sb.append("</tr><tr><td></td><td></td><td></td><td></td><td>" + rFile + "</td>");
                }
            }
            sb.append("</tr>");
        }
        sb.append("</table></html>");
        jTextSummary.setText(sb.toString());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextSummary = new javax.swing.JEditorPane();
        jPanelBottom = new javax.swing.JPanel();
        jButtonDismiss = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTextSummary.setEditable(false);
        jTextSummary.setContentType("text/html");
        jScrollPane1.setViewportView(jTextSummary);

        org.jdesktop.layout.GroupLayout jPanelCenterLayout = new org.jdesktop.layout.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );
        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jButtonDismiss.setText("Dismiss");
        jButtonDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDismissActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelBottomLayout = new org.jdesktop.layout.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomLayout.createSequentialGroup()
                .addContainerGap(621, Short.MAX_VALUE)
                .add(jButtonDismiss)
                .addContainerGap())
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonDismiss)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add(jPanelBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }//GEN-LAST:event_closeDialog
        
    private void jButtonDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDismissActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonDismissActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SummaryDialog().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDismiss;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jTextSummary;
    // End of variables declaration//GEN-END:variables
    
}
